name: Check & Build on Release

on:
  schedule:
    - cron: 2 2 * * *
  workflow_dispatch:

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      latest: ${{ steps.get.outputs.latest }}
      changed: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
      - id: get
        run: |
          latest=$(curl -s https://api.github.com/repos/zerotier/ZeroTierOne/releases/latest \
                   | jq -r '.tag_name')
          echo "::set-output name=latest::$latest"
      - id: check
        run: |
          old=$(cat LAST_VERSION 2>/dev/null || echo "")
          if [ "$old" != "${{ steps.get.outputs.latest }}" ]; then
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=changed::false"
      - name: commit version
        if: steps.check.outputs.changed == 'true'
        run: |
          echo "${{ steps.get.outputs.latest }}" > LAST_VERSION
          git config user.name github-actions
          git config user.email actions@github.com
          git commit -am "Update last ZT version to ${{ steps.get.outputs.latest }}"
          git push

  build:
    if: needs.detect.outputs.changed == 'true'
    needs: detect
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.detect.outputs.latest }}
