name: Check & Trigger Build on Release

on:
  schedule:
    - cron: 2 2 * * *
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 获取最新 release tag
        id: get_latest
        run: |
          echo "Fetching latest ZeroTier release..."
          TAG=$(curl -s https://api.github.com/repos/zerotier/ZeroTierOne/releases/latest \
            | jq -r .tag_name)
          echo "Latest tag = $TAG"
          VERSION=${TAG#v}
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: 读取旧版本
        id: get_old
        run: |
          if [ -f LAST_VERSION ]; then
            OLD=$(cat LAST_VERSION)
          else
            OLD="none"
          fi
          echo "old_version=$OLD" >> "$GITHUB_OUTPUT"

      - name: 判断是否为新版本
        id: version_changed
        run: |
          echo "旧版本: ${{ steps.get_old.outputs.old_version }}，新版本: ${{ steps.get_latest.outputs.version }}"
          if [ "${{ steps.get_old.outputs.old_version }}" != "${{ steps.get_latest.outputs.version }}" ]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "changed=false" >> "$GITHUB_OUTPUT"
          fi

      - name: 更新 LAST_VERSION 并提交
        if: steps.version_changed.outputs.changed == 'true'
        run: |
          echo "${{ steps.get_latest.outputs.version }}" > LAST_VERSION
          git config user.name github-actions
          git config user.email actions@github.com
          git add LAST_VERSION
          git commit -m "Update last ZT version to ${{ steps.get_latest.outputs.version }}"
          git push

      - name: 触发构建工作流
        if: steps.version_changed.outputs.changed == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: trigger-build
