name: Check & Build on Release

on:
  schedule:
    - cron: 2 2 * * *
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 获取最新 release tag
        id: get_latest
        run: |
          echo "Fetching latest ZeroTier release..."
          TAG=$(curl -s https://api.github.com/repos/zerotier/ZeroTierOne/releases/latest \
            | jq -r .tag_name)
          echo "Latest tag = $TAG"
          VERSION=${TAG#v}
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: 写入 LAST_VERSION
        run: |
          VERSION=${{ steps.get_latest.outputs.version }}
          echo "$VERSION" > LAST_VERSION

      - name: 提交更新
        run: |
          git config user.name github-actions
          git config user.email actions@github.com
          git add LAST_VERSION
          git diff --cached --exit-code || git commit -m "Update last ZT version to $VERSION"
          git push

      - name: 通知
        if: ${{ steps.get_latest.outputs.version != '' }}
        run: echo "✔️ LAST_VERSION 已更新为 ${{ steps.get_latest.outputs.version }}"
